development:
  adapter: postgresql
  encoding: unicode
  database: tridb_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tridb_test
  pool: 5
  username: postgres
  password:
  host: localhost
